function schema = build_ui_schema_v9()
%BUILD_UI_SCHEMA_V9 Return the locked APY v9 user-interface schema.

config = build_default_config_v9();

schema = struct();
schema.metadata = struct( ...
    'schemaVersion', 'apy_v9_ui_schema_v1', ...
    'modelVersion', 'v9', ...
    'configVersion', config.configVersion, ...
    'specFile', 'APY_v9_simple_vs_advanced_spec.md', ...
    'defaultMode', 'simple', ...
    'advancedCollapsedByDefault', true, ...
    'notes', 'UI schema only. Engine logic unchanged.');

schema.simpleFields = [ ...
    make_field('scenarioLabel', 'Scenario name', 'simple', 'text', config.scenarioLabel, ...
        'nonempty text', {}, 'User-facing label for this APY scenario.', 'scenarioLabel'); ...
    make_field('ltbiPrevalence', 'LTBI prevalence target', 'simple', 'probability', config.ltbiPrevalence, ...
        'empty or scalar in (0,1)', {}, 'Target LTBI prevalence for calibration. Leave empty to use APY defaults.', 'ltbiPrevalence'); ...
    make_field('activeTBPrevalence', 'Active TB prevalence target', 'simple', 'probability', config.activeTBPrevalence, ...
        'empty or scalar in (0,1)', {}, 'Target active TB prevalence for calibration. Leave empty to use APY defaults.', 'activeTBPrevalence'); ...
    make_field('ageDistributionFile', 'Age distribution file', 'simple', 'file', config.ageDistributionFile, ...
        'empty or existing file path', {}, 'Upload or select an age distribution file. CSV is preferred.', 'ageDistributionFile'); ...
    make_field('riskPrev.contact', 'Close contact prevalence', 'simple', 'vector_or_scalar', config.riskPrev.contact, ...
        'empty, scalar in [0,1], or 3-element vector in [0,1]', {}, 'Overall prevalence or 3 age-band prevalences for close contact.', 'riskPrev.contact'); ...
    make_field('riskPrev.MJ', 'Marijuana use prevalence', 'simple', 'vector_or_scalar', config.riskPrev.MJ, ...
        'empty, scalar in [0,1], or 3-element vector in [0,1]', {}, 'Overall prevalence or 3 age-band prevalences for marijuana use.', 'riskPrev.MJ'); ...
    make_field('riskPrev.renal', 'Renal disease prevalence', 'simple', 'vector_or_scalar', config.riskPrev.renal, ...
        'empty, scalar in [0,1], or 3-element vector in [0,1]', {}, 'Overall prevalence or 3 age-band prevalences for renal disease.', 'riskPrev.renal'); ...
    make_field('riskPrev.diabetes', 'Diabetes prevalence', 'simple', 'vector_or_scalar', config.riskPrev.diabetes, ...
        'empty, scalar in [0,1], or 3-element vector in [0,1]', {}, 'Overall prevalence or 3 age-band prevalences for diabetes.', 'riskPrev.diabetes'); ...
    make_field('riskPrev.smoking', 'Smoking prevalence', 'simple', 'vector_or_scalar', config.riskPrev.smoking, ...
        'empty, scalar in [0,1], or 3-element vector in [0,1]', {}, 'Overall prevalence or 3 age-band prevalences for smoking.', 'riskPrev.smoking'); ...
    make_field('riskPrev.cld', 'Chronic lung disease prevalence', 'simple', 'vector_or_scalar', config.riskPrev.cld, ...
        'empty, scalar in [0,1], or 3-element vector in [0,1]', {}, 'Overall prevalence or 3 age-band prevalences for chronic lung disease.', 'riskPrev.cld'); ...
    make_field('riskPrev.alcohol', 'Alcohol / drugs prevalence', 'simple', 'vector_or_scalar', config.riskPrev.alcohol, ...
        'empty, scalar in [0,1], or 3-element vector in [0,1]', {}, 'Overall prevalence or 3 age-band prevalences for alcohol or drugs.', 'riskPrev.alcohol'); ...
    make_field('riskPrev.female', 'Female prevalence', 'simple', 'probability', config.riskPrev.female, ...
        'empty or scalar in [0,1]', {}, 'Overall female prevalence. Scalar only.', 'riskPrev.female'); ...
    make_field('riskPrev.BCG', 'BCG prevalence', 'simple', 'probability', config.riskPrev.BCG, ...
        'empty or scalar in [0,1]', {}, 'Overall BCG prevalence. Scalar only.', 'riskPrev.BCG'); ...
    make_field('testType', 'Test choice', 'simple', 'select', config.testType, ...
        'one of allowedValues', {'IGRA', 'TST'}, 'Select the LTBI screening test.', 'testType'); ...
    make_field('regimen', 'Treatment choice', 'simple', 'select', config.regimen, ...
        'one of allowedValues', {'3HP', '4R', '3HR', '6H', '9H'}, 'Select the preventive treatment regimen.', 'regimen'); ...
    make_field('pStartTPT', 'Treatment start probability', 'simple', 'probability', config.pStartTPT, ...
        'empty or scalar in [0,1]', {}, 'Probability of starting treatment after being eligible or test-positive.', 'pStartTPT'); ...
    make_field('regimenPComplete', 'Completion probability', 'simple', 'probability', config.regimenPComplete, ...
        'empty or scalar in [0,1]', {}, 'Marginal probability of completing the chosen regimen among starters.', 'regimenPComplete'); ...
    make_field('regimenADRstop', 'ADR stop probability', 'simple', 'probability', config.regimenADRstop, ...
        'empty or scalar in [0,1]', {}, 'Probability of stopping treatment because of an adverse drug reaction.', 'regimenADRstop'); ...
    make_field('regimenEffFull', 'Full-course efficacy', 'simple', 'probability', config.regimenEffFull, ...
        'empty or scalar in [0,1]', {}, 'Protective efficacy after full treatment completion.', 'regimenEffFull'); ...
    make_field('screeningStrategy', 'Screening strategy', 'simple', 'select', config.screeningStrategy, ...
        'one of allowedValues', {'random', 'ltbi', 'cure', 'prevent'}, 'How screening candidates are prioritised.', 'screeningStrategy'); ...
    make_field('screenCoverage', 'Screening coverage', 'simple', 'probability', config.screenCoverage, ...
        'scalar in [0,1]', {}, 'Proportion of the cohort screened.', 'screenCoverage')];

schema.advancedFields = [ ...
    make_field('ageDistributionTable', 'Age distribution table', 'advanced', 'table', config.ageDistributionTable, ...
        'table; mutually exclusive with ageDistributionFile', {}, 'Optional age distribution table input instead of a file.', 'ageDistributionTable'); ...
    make_field('ageDistributionSheet', 'Age distribution sheet', 'advanced', 'text', config.ageDistributionSheet, ...
        'scalar sheet index or sheet name', {}, 'Spreadsheet sheet used when reading age distribution from Excel.', 'ageDistributionSheet'); ...
    make_field('age85PlusMax', 'Age 85+ upper bound', 'advanced', 'number', config.age85PlusMax, ...
        'scalar >= 85', {}, 'Upper bound used when expanding the 85+ age band.', 'age85PlusMax'); ...
    make_field('screenWindow', 'Screen window', 'advanced', 'number', config.screenWindow, ...
        'scalar > 0', {}, 'Duration of the screening window in years.', 'screenWindow'); ...
    make_field('followHorizon', 'Follow-up horizon', 'advanced', 'number', config.followHorizon, ...
        'scalar > 0 and > screenWindow', {}, 'Follow-up duration for outcomes in years.', 'followHorizon'); ...
    make_field('earlyLateRatio', 'Early/late progression ratio', 'advanced', 'number', config.earlyLateRatio, ...
        'empty or scalar >= 1', {}, 'Natural-history tuning parameter controlling early versus late progression.', 'earlyLateRatio'); ...
    make_field('targetAgeOR', 'Age OR target for LTBI calibration', 'advanced', 'number', config.targetAgeOR, ...
        'scalar > 0', {}, 'Calibration target for LTBI age odds ratio.', 'targetAgeOR'); ...
    make_field('testSensitivity', 'IGRA sensitivity', 'advanced', 'probability', config.testSensitivity, ...
        'empty or scalar in [0,1]', {}, 'Override for IGRA sensitivity.', 'testSensitivity'); ...
    make_field('testSpecificity', 'IGRA specificity', 'advanced', 'probability', config.testSpecificity, ...
        'empty or scalar in [0,1]', {}, 'Override for IGRA specificity.', 'testSpecificity'); ...
    make_field('tstSensitivity', 'TST sensitivity', 'advanced', 'probability', config.tstSensitivity, ...
        'empty or scalar in [0,1]', {}, 'Override for TST sensitivity.', 'tstSensitivity'); ...
    make_field('tstSpecificityBCG', 'TST specificity in BCG-vaccinated', 'advanced', 'probability', config.tstSpecificityBCG, ...
        'empty or scalar in [0,1]', {}, 'Override for TST specificity in BCG-vaccinated people.', 'tstSpecificityBCG'); ...
    make_field('tstSpecificityNoBCG', 'TST specificity in non-BCG', 'advanced', 'probability', config.tstSpecificityNoBCG, ...
        'empty or scalar in [0,1]', {}, 'Override for TST specificity in non-BCG people.', 'tstSpecificityNoBCG'); ...
    make_field('diseaseOR.contact', 'Progression OR: close contact', 'advanced', 'number', config.diseaseOR.contact, ...
        'empty or scalar > 0', {}, 'Override for disease progression odds ratio for close contact.', 'diseaseOR.contact'); ...
    make_field('diseaseOR.MJ', 'Progression OR: marijuana use', 'advanced', 'number', config.diseaseOR.MJ, ...
        'empty or scalar > 0', {}, 'Override for disease progression odds ratio for marijuana use.', 'diseaseOR.MJ'); ...
    make_field('diseaseOR.renal', 'Progression OR: renal disease', 'advanced', 'number', config.diseaseOR.renal, ...
        'empty or scalar > 0', {}, 'Override for disease progression odds ratio for renal disease.', 'diseaseOR.renal'); ...
    make_field('diseaseOR.diabetes', 'Progression OR: diabetes', 'advanced', 'number', config.diseaseOR.diabetes, ...
        'empty or scalar > 0', {}, 'Override for disease progression odds ratio for diabetes.', 'diseaseOR.diabetes'); ...
    make_field('diseaseOR.smoking', 'Progression OR: smoking', 'advanced', 'number', config.diseaseOR.smoking, ...
        'empty or scalar > 0', {}, 'Override for disease progression odds ratio for smoking.', 'diseaseOR.smoking'); ...
    make_field('diseaseOR.cld', 'Progression OR: chronic lung disease', 'advanced', 'number', config.diseaseOR.cld, ...
        'empty or scalar > 0', {}, 'Override for disease progression odds ratio for chronic lung disease.', 'diseaseOR.cld'); ...
    make_field('diseaseOR.alcohol', 'Progression OR: alcohol / drugs', 'advanced', 'number', config.diseaseOR.alcohol, ...
        'empty or scalar > 0', {}, 'Override for disease progression odds ratio for alcohol or drugs.', 'diseaseOR.alcohol'); ...
    make_field('N', 'Cohort size', 'advanced', 'number', config.N, ...
        'scalar > 0', {}, 'Number of individuals simulated in each cohort.', 'N'); ...
    make_field('nReps', 'Number of replicates', 'advanced', 'number', config.nReps, ...
        'scalar > 0', {}, 'Number of Monte Carlo replicates.', 'nReps'); ...
    make_field('seed', 'Random seed', 'advanced', 'number', config.seed, ...
        'scalar >= 0', {}, 'Random seed for reproducibility.', 'seed'); ...
    make_field('partialShortCourseMode', 'Partial-course efficacy rule', 'advanced', 'select', config.partialShortCourseMode, ...
        'empty or one of allowedValues', {'threshold80', 'linear', 'none'}, 'Rule used for partial-course efficacy if treatment is not completed.', 'partialShortCourseMode'); ...
    make_field('partialDoseFractionADR', 'Partial dose fraction after ADR stop', 'advanced', 'probability', config.partialDoseFractionADR, ...
        'empty or scalar in [0,1]', {}, 'Fraction of the regimen received when treatment stops due to ADR.', 'partialDoseFractionADR'); ...
    make_field('partialDoseFractionOther', 'Partial dose fraction after other stop', 'advanced', 'probability', config.partialDoseFractionOther, ...
        'empty or scalar in [0,1]', {}, 'Fraction of the regimen received when treatment stops for other reasons.', 'partialDoseFractionOther')];

schema.outputGroups = [ ...
    make_output_group('headline', 'Headline Results', 'core', { ...
        make_output_ref('nScreened', 'Number screened', 'core', 'results.summary metric row'), ...
        make_output_ref('nTotalCoursesStarted', 'Number starting treatment', 'core', 'results.summary metric row'), ...
        make_output_ref('nTotalCoursesCompleted', 'Number completing treatment', 'core', 'results.summary metric row'), ...
        make_output_ref('nFalsePositiveTreated', 'Number of false positives treated', 'core', 'results.summary metric row'), ...
        make_output_ref('nCuredInfection', 'Number of infections protected / cured', 'core', 'results.summary metric row'), ...
        make_output_ref('nPreventedActiveTB', 'Number of active TB cases prevented', 'core', 'results.summary metric row'), ...
        make_output_ref('NNS_cureInfection', 'NNS to protect one infection', 'core', 'results.summary metric row'), ...
        make_output_ref('NNS_preventActiveTB', 'NNS to prevent one active TB case', 'core', 'results.summary metric row'), ...
        make_output_ref('NNT_started_cureInfection', 'NNT to protect one infection', 'core', 'results.summary metric row'), ...
        make_output_ref('NNT_started_preventActiveTB', 'NNT to prevent one active TB case', 'core', 'results.summary metric row')}); ...
    make_output_group('targetedVsRandom', 'Targeted vs Random', 'addOn', { ...
        make_output_ref('run_tb_screening_compare_strategies_v9', 'Strategy comparison table', 'addOn', 'add-on script output'), ...
        make_output_ref('run_tb_screening_targeted_gradient_v9', 'Targeted gradient comparison', 'addOn', 'add-on script output'), ...
        make_output_ref('run_tb_screening_targeting_profile_v9', 'Targeting profile tables', 'addOn', 'add-on script output')}); ...
    make_output_group('doNothing', 'Do-Nothing Comparator', 'addOn', { ...
        make_output_ref('run_tb_screening_do_nothing_v9', 'Do-nothing summary', 'addOn', 'add-on script output')}); ...
    make_output_group('attributableRisk', 'Attributable Risk', 'addOn', { ...
        make_output_ref('run_tb_screening_reactivation_attributable_v9', 'Attributable-risk summary and table', 'addOn', 'add-on script output')}); ...
    make_output_group('downloads', 'Downloads', 'core', { ...
        make_output_ref('summaryCsv', 'Summary CSV', 'core', 'export_results_v9 output'), ...
        make_output_ref('keyMetricsCsv', 'Key metrics CSV', 'core', 'export_results_v9 output'), ...
        make_output_ref('chartFiles', 'Chart/image exports', 'future', 'future consolidated export surface')}); ...
    make_output_group('technicalDetails', 'Technical Details', 'core', { ...
        make_output_ref('calibration', 'Calibration details', 'core', 'results.calibration'), ...
        make_output_ref('exampleCohort', 'Example cohort table', 'core', 'results.exampleCohort'), ...
        make_output_ref('raw', 'Full raw results table', 'core', 'results.raw'), ...
        make_output_ref('interfaceConfig', 'Scenario config used', 'core', 'results.interfaceConfig')}) ...
    ];
end

function field = make_field(internalName, label, mode, inputType, defaultValue, validationRule, allowedValues, helpText, sourceConfigField)
field = struct( ...
    'internalName', internalName, ...
    'label', label, ...
    'mode', mode, ...
    'inputType', inputType, ...
    'defaultValue', defaultValue, ...
    'validationRule', validationRule, ...
    'allowedValues', {allowedValues}, ...
    'helpText', helpText, ...
    'sourceConfigField', sourceConfigField);
end

function group = make_output_group(groupName, label, availability, outputs)
group = struct( ...
    'groupName', groupName, ...
    'label', label, ...
    'availability', availability, ...
    'outputs', {outputs});
end

function output = make_output_ref(outputName, label, availability, backendSource)
output = struct( ...
    'outputName', outputName, ...
    'label', label, ...
    'availability', availability, ...
    'backendSource', backendSource);
end
