function uiState = economics_config_to_ui_state_v9(econConfig)
%ECONOMICS_CONFIG_TO_UI_STATE_V9 Convert economics config to flat UI state.

if nargin < 1 || isempty(econConfig)
    econConfig = build_default_economics_config_v9();
end

uiState = struct();
uiState.fieldValues = struct();

fields = economics_ui_field_map_v9();
for i = 1:numel(fields)
    uiState.fieldValues.(fields(i).componentName) = get_nested_field(econConfig, fields(i).configPath);
end
end

function fields = economics_ui_field_map_v9()
fields = struct( ...
    'componentName', { ...
        'CurrencyCodeEditField', ...
        'PriceYearEditField', ...
        'LocationLabelEditField', ...
        'SourceNotesTextArea', ...
        'ProgramCostBasisDropDown', ...
        'IGRACostEditField', ...
        'TSTCostEditField', ...
        'Regimen3HPCostEditField', ...
        'Regimen4RCostEditField', ...
        'Regimen3HRCostEditField', ...
        'Regimen6HCostEditField', ...
        'Regimen9HCostEditField', ...
        'FalsePositiveIncrementalCostEditField', ...
        'ActiveTBDiseaseCostEditField', ...
        'ProgramSetupCostEditField', ...
        'ProgramRunningCostEditField'}, ...
    'configPath', { ...
        'metadata.currencyCode', ...
        'metadata.priceYear', ...
        'metadata.locationLabel', ...
        'metadata.sourceNotes', ...
        'metadata.programCostBasis', ...
        'costs.test.IGRA', ...
        'costs.test.TST', ...
        'costs.regimen.x3HP', ...
        'costs.regimen.x4R', ...
        'costs.regimen.x3HR', ...
        'costs.regimen.x6H', ...
        'costs.regimen.x9H', ...
        'costs.falsePositiveIncrementalPerPerson', ...
        'costs.activeTBDiseasePerCase', ...
        'costs.programSetupTotal', ...
        'costs.programRunningTotal'});
end

function value = get_nested_field(s, path)
value = [];
parts = strsplit(path, '.');
value = s;
for i = 1:numel(parts)
    if ~isstruct(value) || ~isfield(value, parts{i})
        value = [];
        return;
    end
    value = value.(parts{i});
end
end
