function comparison = run_tb_screening_compare_strategies_v9(screeningStrategy, screenCoverage, nReps)
% Compare IGRA/TST crossed with 4R, 3HR, 6H, and 9H using tb_screening_mc_model_v9.
%
% Optional inputs:
%   screeningStrategy : 'random' (default), 'ltbi', 'cure', or 'prevent'
%   screenCoverage    : cumulative screening coverage (default 624/770)
%   nReps             : number of Monte Carlo replicates (default 2000)

thisFile = mfilename('fullpath');
[thisDir, ~, ~] = fileparts(thisFile);
csvFile = fullfile(thisDir, 'default_data.csv');

if nargin < 1 || isempty(screeningStrategy)
    screeningStrategy = 'random';
end
if nargin < 2 || isempty(screenCoverage)
    screenCoverage = 624/770;
end
if nargin < 3 || isempty(nReps)
    nReps = 2000;
end

tests = {'IGRA','TST'};
regimens = {'3HP','4R','3HR','6H','9H'};

row = 0;
nRows = numel(tests) * numel(regimens);
rows = repmat(struct( ...
    'testType', '', ...
    'regimen', '', ...
    'screeningStrategy', '', ...
    'screenCoverage', NaN, ...
    'tstSpecificityBCG', NaN, ...
    'tstSpecificityNoBCG', NaN, ...
    'pComplete', NaN, ...
    'pADRstop', NaN, ...
    'effFull', NaN, ...
    'partialEff50', NaN, ...
    'partialEff80', NaN, ...
    'medFalsePositiveTests', NaN, ...
    'medFalsePositiveTestsBCG', NaN, ...
    'medExcessFalsePositiveTestsDueToBCG', NaN, ...
    'medFalsePositiveTreated', NaN, ...
    'medFalsePositiveTreatedBCG', NaN, ...
    'medExcessCoursesDueToBCG', NaN, ...
    'medCoursesStarted', NaN, ...
    'medCoursesCompleted', NaN, ...
    'medADRstop', NaN, ...
    'medCompletionRate', NaN, ...
    'medADRrate', NaN, ...
    'medFalsePositiveRateBCG', NaN, ...
    'medFalsePositiveRateNoBCG', NaN, ...
    'medBCGAttribFalsePositiveRate', NaN, ...
    'medCuredInfection', NaN, ...
    'medCuredInfectionPartial', NaN, ...
    'medPreventedActiveTB', NaN, ...
    'medPreventedActiveTBPartial', NaN, ...
    'pooledNNS_cure', NaN, ...
    'pooledNNS_prevent', NaN, ...
    'pooledNNT_cure', NaN, ...
    'pooledNNT_prevent', NaN), nRows, 1);

for i = 1:numel(tests)
    for j = 1:numel(regimens)
        row = row + 1;
        res = tb_screening_mc_model_v9(csvFile, ...
            'N', 1500, ...
            'nReps', nReps, ...
            'screenWindow', 2, ...
            'followHorizon', 20, ...
            'testType', tests{i}, ...
            'regimen', regimens{j}, ...
            'screeningStrategy', screeningStrategy, ...
            'screenCoverage', screenCoverage, ...
            'seed', 1);

        rows(row).testType = tests{i};
        rows(row).regimen = regimens{j};
        rows(row).screeningStrategy = screeningStrategy;
        rows(row).screenCoverage = screenCoverage;
        rows(row).tstSpecificityBCG = res.strategy.tstSpecificityBCG;
        rows(row).tstSpecificityNoBCG = res.strategy.tstSpecificityNoBCG;
        rows(row).pComplete = res.strategy.pComplete;
        rows(row).pADRstop = res.strategy.pADRstop;
        rows(row).effFull = res.strategy.effFull;
        rows(row).partialEff50 = res.strategy.partialEfficacyAt50pct;
        rows(row).partialEff80 = res.strategy.partialEfficacyAt80pct;
        rows(row).medFalsePositiveTests = get_metric(res.summary, 'nFalsePositiveTests');
        rows(row).medFalsePositiveTestsBCG = get_metric(res.summary, 'nFalsePositiveTestsBCG');
        rows(row).medExcessFalsePositiveTestsDueToBCG = get_metric(res.summary, 'nExcessFalsePositiveTestsDueToBCG');
        rows(row).medFalsePositiveTreated = get_metric(res.summary, 'nFalsePositiveTreated');
        rows(row).medFalsePositiveTreatedBCG = get_metric(res.summary, 'nFalsePositiveTreatedBCG');
        rows(row).medExcessCoursesDueToBCG = get_metric(res.summary, 'nExcessCoursesDueToBCG');
        rows(row).medCoursesStarted = get_metric(res.summary, 'nStartTPT');
        rows(row).medCoursesCompleted = get_metric(res.summary, 'nCompleteTPT');
        rows(row).medADRstop = get_metric(res.summary, 'nADRstop');
        rows(row).medCompletionRate = get_metric(res.summary, 'completionRateObserved');
        rows(row).medADRrate = get_metric(res.summary, 'adrRateObserved');
        rows(row).medFalsePositiveRateBCG = get_metric(res.summary, 'falsePositiveRateObservedBCG');
        rows(row).medFalsePositiveRateNoBCG = get_metric(res.summary, 'falsePositiveRateObservedNoBCG');
        rows(row).medBCGAttribFalsePositiveRate = get_metric(res.summary, 'bcgAttributableFalsePositiveRateObserved');
        rows(row).medCuredInfection = get_metric(res.summary, 'nCuredInfection');
        rows(row).medCuredInfectionPartial = get_metric(res.summary, 'nCuredInfectionPartial');
        rows(row).medPreventedActiveTB = get_metric(res.summary, 'nPreventedActiveTB');
        rows(row).medPreventedActiveTBPartial = get_metric(res.summary, 'nPreventedActiveTBPartial');
        rows(row).pooledNNS_cure = sum(res.raw.nScreened) / sum(res.raw.nCuredInfection);
        rows(row).pooledNNS_prevent = sum(res.raw.nScreened) / sum(res.raw.nPreventedActiveTB);
        rows(row).pooledNNT_cure = sum(res.raw.nStartTPT) / sum(res.raw.nCuredInfection);
        rows(row).pooledNNT_prevent = sum(res.raw.nStartTPT) / sum(res.raw.nPreventedActiveTB);
    end
end

comparison = struct2table(rows, 'AsArray', true);
disp(comparison)
end

function val = get_metric(summaryTbl, metricName)
idx = strcmp(summaryTbl.Metric, metricName);
if any(idx)
    val = summaryTbl.Median(idx);
else
    val = NaN;
end
end
