function econConfig = ui_state_to_economics_config_v9(uiState, baseConfig)
%UI_STATE_TO_ECONOMICS_CONFIG_V9 Convert flat UI state to economics config.

if nargin < 2 || isempty(baseConfig)
    baseConfig = build_default_economics_config_v9();
end

econConfig = baseConfig;
if ~isstruct(uiState) || ~isfield(uiState, 'fieldValues') || ~isstruct(uiState.fieldValues)
    return;
end

fields = economics_ui_field_map_v9();
for i = 1:numel(fields)
    componentName = fields(i).componentName;
    if isfield(uiState.fieldValues, componentName)
        econConfig = set_nested_field(econConfig, fields(i).configPath, ...
            normalize_ui_value(uiState.fieldValues.(componentName)));
    end
end
end

function fields = economics_ui_field_map_v9()
fields = struct( ...
    'componentName', { ...
        'CurrencyCodeEditField', ...
        'PriceYearEditField', ...
        'LocationLabelEditField', ...
        'SourceNotesTextArea', ...
        'ProgramCostBasisDropDown', ...
        'IGRACostEditField', ...
        'TSTCostEditField', ...
        'Regimen3HPCostEditField', ...
        'Regimen4RCostEditField', ...
        'Regimen3HRCostEditField', ...
        'Regimen6HCostEditField', ...
        'Regimen9HCostEditField', ...
        'FalsePositiveIncrementalCostEditField', ...
        'ActiveTBDiseaseCostEditField', ...
        'ProgramSetupCostEditField', ...
        'ProgramRunningCostEditField'}, ...
    'configPath', { ...
        'metadata.currencyCode', ...
        'metadata.priceYear', ...
        'metadata.locationLabel', ...
        'metadata.sourceNotes', ...
        'metadata.programCostBasis', ...
        'costs.test.IGRA', ...
        'costs.test.TST', ...
        'costs.regimen.x3HP', ...
        'costs.regimen.x4R', ...
        'costs.regimen.x3HR', ...
        'costs.regimen.x6H', ...
        'costs.regimen.x9H', ...
        'costs.falsePositiveIncrementalPerPerson', ...
        'costs.activeTBDiseasePerCase', ...
        'costs.programSetupTotal', ...
        'costs.programRunningTotal'});
end

function s = set_nested_field(s, path, value)
parts = strsplit(path, '.');
if numel(parts) == 1
    s.(parts{1}) = value;
    return;
end

head = parts{1};
tail = strjoin(parts(2:end), '.');
if ~isfield(s, head) || ~isstruct(s.(head))
    s.(head) = struct();
end
s.(head) = set_nested_field(s.(head), tail, value);
end

function value = normalize_ui_value(value)
if iscell(value)
    value = string(value);
end
if isstring(value)
    if isempty(value)
        value = '';
    elseif isscalar(value)
        value = char(value);
    else
        value = char(strjoin(value(:), newline));
    end
end
end
